-- MySQL Script generated by MySQL Workbench
-- Thu Dec 19 14:27:40 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ecommerce
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ecommerce` DEFAULT CHARACTER SET utf8 ;
USE `ecommerce`;

-- -----------------------------------------------------
-- Table `ecommerce`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `ecommerce`.`Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `Endereco` VARCHAR(45) NOT NULL,
  `Nome` VARCHAR(15) NOT NULL COMMENT 'Adicionar constraint de unicidade para (nome completo)\nunique (Nome, Sobrenome)',
  `Sobrenome` VARCHAR(25) NOT NULL,
  `DataNascimento` DATE NOT NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;
ALTER TABLE Cliente auto_increment = 1;

-- -----------------------------------------------------
-- Table `ecommerce`.`Cliente_CPF`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce`.`Cliente_CPF` ;

CREATE TABLE IF NOT EXISTS `ecommerce`.`Cliente_CPF` (
  `Cliente_idCliente` INT NOT NULL,
  `CPF` CHAR(11) NOT NULL,
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC) VISIBLE,
  INDEX `fk_Cliente_CPF_Cliente1_idx` (`Cliente_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente_CPF_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `ecommerce`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `ecommerce`.`Cliente_CNPJ`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce`.`Cliente_CNPJ` ;

CREATE TABLE IF NOT EXISTS `ecommerce`.`Cliente_CNPJ` (
  `Cliente_idCliente` INT NOT NULL,
  `Razao_Social` VARCHAR(45) NOT NULL,
  `CNPJ` VARCHAR(45) NOT NULL,
  INDEX `fk_Cliente_CNPJ_Cliente1_idx` (`Cliente_idCliente` ASC) VISIBLE,
  UNIQUE INDEX `CNPJ_UNIQUE` (`CNPJ` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente_CNPJ_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `ecommerce`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `ecommerce`.`Pagamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce`.`Pagamento` ;

CREATE TABLE IF NOT EXISTS `ecommerce`.`Pagamento` (
  `Cliente_idCliente` INT NOT NULL,
  `idPagamento` INT NOT NULL AUTO_INCREMENT,
  `Tipo` ENUM("Crédito", "Débito") NOT NULL,
  `Identificador` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPagamento`),
  INDEX `fk_Pagamento_Cliente1_idx` (`Cliente_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Pagamento_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `ecommerce`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
ALTER TABLE Pagamento auto_increment = 1;

-- -----------------------------------------------------
-- Table `ecommerce`.`Pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce`.`Pedido` ;

CREATE TABLE IF NOT EXISTS `ecommerce`.`Pedido` (
  `idPedido` INT NOT NULL AUTO_INCREMENT,
  `Status_Pedido` ENUM("Processando", "Enviado", "A Caminho", "Rota de Entrega", "Finalizado") NULL DEFAULT 'Processando',
  `Descricao` VARCHAR(45) NULL,
  `Status_de_Entrega` VARCHAR(45) NULL,
  `Frete` FLOAT NULL,
  `Rastreio` VARCHAR(45) NULL,
  `Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idPedido`, `Cliente_idCliente`),
  INDEX `fk_Pedido_Cliente1_idx` (`Cliente_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Pedido_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `ecommerce`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
ALTER TABLE Pedido auto_increment = 1;

-- -----------------------------------------------------
-- Table `ecommerce`.`Produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce`.`Produto` ;

CREATE TABLE IF NOT EXISTS `ecommerce`.`Produto` (
  `idProduto` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `Descricao` VARCHAR(45) NOT NULL,
  `Valor` FLOAT NOT NULL,
  `Categoria` ENUM('Eletronico', 'Roupa', 'Brinquedo', 'Comida') NOT NULL,
  PRIMARY KEY (`idProduto`))
ENGINE = InnoDB;
ALTER TABLE Produto auto_increment = 1;

-- -----------------------------------------------------
-- Table `ecommerce`.`Fornecedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce`.`Fornecedor` ;

CREATE TABLE IF NOT EXISTS `ecommerce`.`Fornecedor` (
  `idFornecedor` INT NOT NULL AUTO_INCREMENT,
  `Razao_Social` VARCHAR(45) NOT NULL,
  `CNPJ` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idFornecedor`),
  UNIQUE INDEX `Razao_Social_UNIQUE` (`Razao_Social` ASC) VISIBLE,
  UNIQUE INDEX `CNPJ_UNIQUE` (`CNPJ` ASC) VISIBLE)
ENGINE = InnoDB;
ALTER TABLE Fornecedor auto_increment = 1;

-- -----------------------------------------------------
-- Table `ecommerce`.`Disponibiliza_um_Produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce`.`Disponibiliza_um_Produto` ;

CREATE TABLE IF NOT EXISTS `ecommerce`.`Disponibiliza_um_Produto` (
  `Fornecedor_idFornecedor` INT NOT NULL,
  `Produto_idProduto` INT NOT NULL,
  PRIMARY KEY (`Fornecedor_idFornecedor`, `Produto_idProduto`),
  INDEX `fk_Fornecedor_has_Produto_Produto1_idx` (`Produto_idProduto` ASC) VISIBLE,
  INDEX `fk_Fornecedor_has_Produto_Fornecedor1_idx` (`Fornecedor_idFornecedor` ASC) VISIBLE,
  CONSTRAINT `fk_Fornecedor_has_Produto_Fornecedor1`
    FOREIGN KEY (`Fornecedor_idFornecedor`)
    REFERENCES `ecommerce`.`Fornecedor` (`idFornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fornecedor_has_Produto_Produto1`
    FOREIGN KEY (`Produto_idProduto`)
    REFERENCES `ecommerce`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `ecommerce`.`Estoque`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce`.`Estoque` ;

CREATE TABLE IF NOT EXISTS `ecommerce`.`Estoque` (
  `idEstoque` INT NOT NULL AUTO_INCREMENT,
  `Endereco` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEstoque`))
ENGINE = InnoDB;
ALTER TABLE Estoque auto_increment = 1;

-- -----------------------------------------------------
-- Table `ecommerce`.`Produto_em_Estoque`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce`.`Produto_em_Estoque` ;

CREATE TABLE IF NOT EXISTS `ecommerce`.`Produto_em_Estoque` (
  `Produto_idProduto` INT NOT NULL,
  `Estoque_idEstoque` INT NOT NULL,
  `Quantidade` INT NULL,
  PRIMARY KEY (`Produto_idProduto`, `Estoque_idEstoque`),
  INDEX `fk_Produto_has_Estoque_Estoque1_idx` (`Estoque_idEstoque` ASC) VISIBLE,
  INDEX `fk_Produto_has_Estoque_Produto1_idx` (`Produto_idProduto` ASC) VISIBLE,
  CONSTRAINT `fk_Produto_has_Estoque_Produto1`
    FOREIGN KEY (`Produto_idProduto`)
    REFERENCES `ecommerce`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produto_has_Estoque_Estoque1`
    FOREIGN KEY (`Estoque_idEstoque`)
    REFERENCES `ecommerce`.`Estoque` (`idEstoque`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `ecommerce`.`Relacao_produto_Pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce`.`Relacao_produto_Pedido` ;

CREATE TABLE IF NOT EXISTS `ecommerce`.`Relacao_produto_Pedido` (
  `Produto_idProduto` INT NOT NULL,
  `Pedido_idPedido` INT NOT NULL,
  `Quantidade` INT NOT NULL,
  `Status_Produto` ENUM("Em Estoque", "Em Falta") NULL DEFAULT 'Em Estoque',
  PRIMARY KEY (`Produto_idProduto`, `Pedido_idPedido`),
  INDEX `fk_Produto_has_Pedido_Pedido1_idx` (`Pedido_idPedido` ASC) VISIBLE,
  INDEX `fk_Produto_has_Pedido_Produto1_idx` (`Produto_idProduto` ASC) VISIBLE,
  CONSTRAINT `fk_Produto_has_Pedido_Produto1`
    FOREIGN KEY (`Produto_idProduto`)
    REFERENCES `ecommerce`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produto_has_Pedido_Pedido1`
    FOREIGN KEY (`Pedido_idPedido`)
    REFERENCES `ecommerce`.`Pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `ecommerce`.`Terceiro_Vendendor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce`.`TerceiroVendendor` ;

CREATE TABLE IF NOT EXISTS `ecommerce`.`TerceiroVendendor` (
  `idTerceiroVendendor` INT NOT NULL AUTO_INCREMENT,
  `Razao_Social` VARCHAR(45) NOT NULL,
  `Endereco` VARCHAR(45) NOT NULL,
  `CNPJ` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTerceiroVendendor`),
  UNIQUE INDEX `Razao_Social_UNIQUE` (`Razao_Social` ASC) VISIBLE,
  UNIQUE INDEX `CNPJ_UNIQUE` (`CNPJ` ASC) VISIBLE)
ENGINE = InnoDB;
ALTER TABLE TerceiroVendendor auto_increment = 1;

-- -----------------------------------------------------
-- Table `ecommerce`.`Terceiro_Vende_Produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce`.`Terceiro_Vende_Produto` ;

CREATE TABLE IF NOT EXISTS `ecommerce`.`Terceiro_Vende_Produto` (
  `TerceiroVendendor_idTerceiroVendendor` INT NOT NULL,
  `Produto_idProduto` INT NOT NULL,
  `Quantidade` INT NULL,
  PRIMARY KEY (`TerceiroVendendor_idTerceiroVendendor`, `Produto_idProduto`),
  INDEX `fk_Terceiro - Vendendor_has_Produto_Produto1_idx` (`Produto_idProduto` ASC) VISIBLE,
  INDEX `fk_Terceiro - Vendendor_has_Produto_Terceiro - Vendendor1_idx` (`TerceiroVendendor_idTerceiroVendendor` ASC) VISIBLE,
  CONSTRAINT `fk_TerceiroVendendor_has_Produto_TerceiroVendendor1`
    FOREIGN KEY (`TerceiroVendendor_idTerceiroVendendor`)
    REFERENCES `ecommerce`.`TerceiroVendendor` (`idTerceiroVendendor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Terceiro - Vendendor_has_Produto_Produto1`
    FOREIGN KEY (`Produto_idProduto`)
    REFERENCES `ecommerce`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;