-- MySQL Script generated by MySQL Workbench
-- Thu Dec 26 10:02:33 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema oficina
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `oficina` DEFAULT CHARACTER SET utf8 ;
USE `oficina` ;

-- -----------------------------------------------------
-- Table `oficina`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oficina`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `oficina`.`Cliente` (
  `idCliente` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `CPF` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficina`.`Mecanico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oficina`.`Mecanico` ;

CREATE TABLE IF NOT EXISTS `oficina`.`Mecanico` (
  `idMecanico` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Endereco` VARCHAR(45) NOT NULL,
  `Especialidade` VARCHAR(45) NULL,
  `Equipe_idEquipe` INT NULL,
  PRIMARY KEY (`idMecanico`),
  INDEX `fk_Mecanico_Equipe_idx` (`Equipe_idEquipe` ASC) VISIBLE,
  CONSTRAINT `fk_Mecanico_Equipe`
    FOREIGN KEY (`Equipe_idEquipe`)
    REFERENCES `oficina`.`Equipe` (`idEquipe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficina`.`Equipe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oficina`.`Equipe` ;

CREATE TABLE IF NOT EXISTS `oficina`.`Equipe` (
  `idEquipe` INT NOT NULL,
  `Mecanico_idMecanico` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEquipe`, `Mecanico_idMecanico`),
  INDEX `fk_Equipe_Mecanico1_idx` (`Mecanico_idMecanico` ASC) VISIBLE,
  CONSTRAINT `fk_Equipe_Mecanico1`
    FOREIGN KEY (`Mecanico_idMecanico`)
    REFERENCES `oficina`.`Mecanico` (`idMecanico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficina`.`Ordem_de_Serviço`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oficina`.`Ordem_de_Serviço` ;

CREATE TABLE IF NOT EXISTS `oficina`.`Ordem_de_Serviço` (
  `idOrdem_de_Serviço` INT NOT NULL,
  `Emissao` DATETIME NOT NULL,
  `Entrega` VARCHAR(45) NOT NULL,
  `Valor_Total` FLOAT NOT NULL,
  `Status` VARCHAR(45) NOT NULL,
  `Prazo` DATE NOT NULL,
  `Equipe_idEquipe` INT NOT NULL,
  `Veiculo_idVeiculo` INT NOT NULL,
  PRIMARY KEY (`idOrdem_de_Serviço`, `Equipe_idEquipe`, `Veiculo_idVeiculo`),
  INDEX `fk_Ordem_de_Serviço_Equipe1_idx` (`Equipe_idEquipe` ASC) VISIBLE,
  CONSTRAINT `fk_Ordem_de_Serviço_Equipe1`
    FOREIGN KEY (`Equipe_idEquipe`)
    REFERENCES `oficina`.`Equipe` (`idEquipe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficina`.`Veiculo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oficina`.`Veiculo` ;

CREATE TABLE IF NOT EXISTS `oficina`.`Veiculo` (
  `Placa` VARCHAR(45) NOT NULL,
  `Modelo` VARCHAR(45) NOT NULL,
  `Cor` VARCHAR(45) NOT NULL,
  `Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`Cliente_idCliente`, `Placa`),
  INDEX `fk_Veiculo_Cliente1_idx` (`Cliente_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Veiculo_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `oficina`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficina`.`Peca`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oficina`.`Peca` ;

CREATE TABLE IF NOT EXISTS `oficina`.`Peca` (
  `idPeca` INT NOT NULL,
  `Valor` FLOAT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPeca`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficina`.`Servico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oficina`.`Servico` ;

CREATE TABLE IF NOT EXISTS `oficina`.`Servico` (
  `idServico` INT NOT NULL,
  `Valor` FLOAT NOT NULL,
  `Descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idServico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficina`.`Pecas_OS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oficina`.`Pecas_OS` ;

CREATE TABLE IF NOT EXISTS `oficina`.`Pecas_OS` (
  `Peca_idPeca` INT NOT NULL,
  `Ordem_de_Serviço_idOrdem_de_Serviço` INT NOT NULL,
  `Quantidade` INT NOT NULL,
  PRIMARY KEY (`Peca_idPeca`, `Ordem_de_Serviço_idOrdem_de_Serviço`),
  INDEX `fk_Peca_has_Ordem_de_Serviço_Ordem_de_Serviço1_idx` (`Ordem_de_Serviço_idOrdem_de_Serviço` ASC) VISIBLE,
  INDEX `fk_Peca_has_Ordem_de_Serviço_Peca1_idx` (`Peca_idPeca` ASC) VISIBLE,
  CONSTRAINT `fk_Peca_has_Ordem_de_Serviço_Peca1`
    FOREIGN KEY (`Peca_idPeca`)
    REFERENCES `oficina`.`Peca` (`idPeca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Peca_has_Ordem_de_Serviço_Ordem_de_Serviço1`
    FOREIGN KEY (`Ordem_de_Serviço_idOrdem_de_Serviço`)
    REFERENCES `oficina`.`Ordem_de_Serviço` (`idOrdem_de_Serviço`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficina`.`Servicos_OS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oficina`.`Servicos_OS` ;

CREATE TABLE IF NOT EXISTS `oficina`.`Servicos_OS` (
  `Servico_idServico` INT NOT NULL,
  `Ordem_de_Serviço_idOrdem_de_Serviço` INT NOT NULL,
  `Quantidade` INT NULL,
  PRIMARY KEY (`Servico_idServico`, `Ordem_de_Serviço_idOrdem_de_Serviço`),
  INDEX `fk_Servico_has_Ordem_de_Serviço_Ordem_de_Serviço1_idx` (`Ordem_de_Serviço_idOrdem_de_Serviço` ASC) VISIBLE,
  INDEX `fk_Servico_has_Ordem_de_Serviço_Servico1_idx` (`Servico_idServico` ASC) VISIBLE,
  CONSTRAINT `fk_Servico_has_Ordem_de_Serviço_Servico1`
    FOREIGN KEY (`Servico_idServico`)
    REFERENCES `oficina`.`Servico` (`idServico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Servico_has_Ordem_de_Serviço_Ordem_de_Serviço1`
    FOREIGN KEY (`Ordem_de_Serviço_idOrdem_de_Serviço`)
    REFERENCES `oficina`.`Ordem_de_Serviço` (`idOrdem_de_Serviço`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
